Added CustomJSONFormatter to generate Cucumber Reports for executed test cases in an event of Thread Failure
eu-evops/cucumber-runner-maven-plugin pull request #4
Opened 2017-07-12 14:56 UTC by Subrahmanyam83

2017-07-14 13:12 UTC, Subrahmanyam83 commented
Please provide review comments

2017-07-14 13:12 UTC, sponte requested changes

2017-07-14 13:12 UTC, sponte commented on .gitignore
> +*.iml
It's ok for .iml to be in the repo

2017-07-14 13:12 UTC, sponte commented on src/main/java/eu/evops/maven/pluins/cucumber/parallel/CustomJSONFormatter.java
> +package eu.evops.maven.pluins.cucumber.parallel;
Is there a reason why this class does not inherit from JSONFormatter class and only override what it needs?

2017-07-14 13:12 UTC, sponte commented on src/main/java/eu/evops/maven/pluins/cucumber/parallel/CustomJSONFormatter.java
> +public class CustomJSONFormatter implements Reporter, Formatter {
CustomerJSONFormatter name is not descriptive, can you rename to something more meaningful for instance StreamingJSONFormatter and adding appropriate comments to indicate why it's been added?

2017-07-14 13:12 UTC, sponte commented on src/main/java/eu/evops/maven/pluins/cucumber/parallel/Run.java
> +            if(pluginName.matches("^(CustomJSONFormatter|junit)")) {
This code in unnecessary. You should update Merger.get method to return correct merge plugin

2017-07-14 13:12 UTC, sponte commented on src/main/java/eu/evops/maven/pluins/cucumber/parallel/Run.java
> +            if(plugin.endsWith(":")&&!plugin.startsWith("json")) {
Again, this should not be necessary, update getReportFileName method that expects your new json reporter plugin name (absolute)

2017-07-26 10:23 UTC, sponte commented on src/main/java/eu/evops/maven/pluins/cucumber/parallel/Run.java
> +    private boolean getStreamingFormatterValue() throws IOException {
Why does this throw IOException?

2017-07-28 16:24 UTC, sponte commented on pom.xml
> +						1.8
Hey, this should revert back to 1.7 please

2017-07-31 13:28 UTC, sponte approved these changes

2017-07-31 13:32 UTC, merged